prasenjeet-symon/intellectia

packages/server/src/api_auth/index.ts
=> refactor: removing redundant validation on magic_login route

packages/client/src/pages/Authentication/SignUpPage/SignUpPage.tsx
fixed the issue by importing the CSS file
=> Resolves #101 singup page image not showing

packages/client/src/api/apiClient.ts
Issue: #104 
added apiClient.ts to api folder in the React Client
=> added apiClient.ts

.gitignore
prisma migrations to be ignored added in gitignore file
=> ignore prisma migration files

packages/client/src/api/api.ts, packages/client/src/hooks/authentication.hooks.ts
This PR related to issue #112 
Description:
- updated the custom react hook "useLoginWithEmailAndPassword" in packages/client/src/hooks/authentication.hooks.ts
- updated loginWithEmailPassword in packages/client/src/api/api.ts
=> updated useLoginWithEmailAndPassword hook

packages/server/src/seeder/utils.ts
Generate Fake User for Seeding using faker-js
#149
=> Generate Fake User for Seeding

packages/server/src/seeder/utils.ts
fixed #148 
Have updated generateFakeArticle() to return a object(article)
=> Updated  seeder/utils.ts and and changed generateFakeArticle()

packages/client/src/pages/Authentication/LoginPage/LoginPage.tsx
issue : #145 
[2023-10-10 22-17-14.webm](https://github.com/prasenjeet-symon/intellectia/assets/64489317/22473dea-2d7e-4cee-a24e-6ac3afbd74e9)
=> feat : Login Page implemented with Zod Validations

packages/server/src/seeder/utils.ts
Solves issue #146 
Completed markdowntoJSON function as described in issue 146. This function can now read the specified file and return its contents in JSON format.
=> Completed markdownToJSON function as described in issue 146

packages/server/src/api_auth/index.ts, packages/server/src/validators/index.ts
Hook me up if anything is wrong :)
=> fixed: Implement Zod Validation for /google_login API Route #136

packages/server/src/validators/index.ts
I will removed other validator after you approve this approach @prasenjeet-symon
=> optimised validator file

packages/server/src/api/index.ts, packages/server/src/validators/index.ts
Below is the attached screenshot for 3 cases,
=> Added zod validation for id in GET topic/:id route

packages/client/src/api/api.ts, packages/client/src/hooks/authentication.hooks.ts, packages/client/src/pages/Dashboard/FeedPage/FeedPage.tsx
=> implement user logout

packages/recom-server/.env.local, packages/recom-server/.gitignore, packages/recom-server/Dockerfile, packages/recom-server/README.md, packages/recom-server/app.py, packages/recom-server/apps/__init__.py, packages/recom-server/apps/recommendations/__init__.py, packages/recom-server/apps/recommendations/controllers.py, packages/recom-server/apps/recommendations/views.py, packages/recom-server/entrypoint.sh, packages/recom-server/requirements.txt
I'm creating this PR to address below issue: 
https://github.com/prasenjeet-symon/intellectia/issues/215#issue-1954163034
Here's a summary of what's been accomplished:
Server Setup:
-Created a Python-based Flask server named "recom-server."
-Established the necessary project structure, including app.py, the recommendations directory (inside apps), and a virtual environment (venv).
Documentation:
-Crafted a comprehensive README.md file detailing the server's purpose, features, and setup instructions.
-Additionally, I've included information about making a GET request to http://localhost:5000/recommendations/get-recommendation, which returns a JSON response: {"message": "Articles recommendation"} when everything is set up correctly.
The documentation has been carefully prepared to ensure …
=> flask recommendation server setup

packages/client/src/pages/Authentication/SignUpPage/SignUpPage.tsx
=> Hide password when signing up

packages/server/__tests__/utils.test.ts, packages/server/package.json, packages/server/src/seeder/utils.ts
I finished my issue and also edited a few things. I guess I made some extra stuff, hopefully it won't be a problem.
https://github.com/prasenjeet-symon/intellectia/issues/174
=> comment-replies

packages/client/src/api/api.ts, packages/client/src/hooks/authentication.hooks.ts, packages/client/src/types/types.ts
fixes : #128
useSignupWithGoogle hook added successfully
=> useSignupWithGoogle hook added

packages/server/src/api/index.ts, packages/server/src/api_auth/index.ts
Added validators to API Routes.
Closes: #219 
@prasenjeet-symon
Please, have a look
=> Attach Validators Middleware to API Routes

packages/server/src/events/tasks.ts
Resolves: #64 
This ticket will ensure to distribute article story to the author's followers.
=> Task to Distribute Article Story to Authors Followers

packages/server/src/api_auth/index.ts
Fixes: #231 
This PR enhances the code structure by utilizing` res.locals.reqClientData` as the source for client data, removing direct access to `req.body`, `req.query`, and` req.params. `
=> Refactor of magic Route

packages/server/src/api_auth/index.ts
[# 230](https://github.com/prasenjeet-symon/intellectia/issues/230)
This PR enhances the code structure by utilizing res.locals.reqClientData as the source for client data, removing direct access to req.body, req.query, andreq.params.
=> refactor signup router

packages/server/src/api_auth/index.ts
refer  Refactor "/google" Route for Improved Code Structure #233
Done changes as per the comments.
=>  Refactoring google route 233
